bin_path = "users.bin"
csv_path = "users.csv"

tcp_host = "localhost:8080"
http_host = "localhost:8081"

[mysql]
db = "docker"
host = "localhost"
password = "example"
port = 3306
user = "root"

[postgres]
db = "docker"
host = "docker"
password = "docker"
port = 55000
user = "docker"
